name: cd

# Create new release without changes:
# git commit -m "[commit_message]" --allow-empty
# git tag [tag_name]
# git push origin [branch_name] --tags

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:
        inputs:
            version:
                description: "Release version"
                required: true
                type: string

jobs:
    version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Get version from commit tag
              if: github.event_name == 'push'
              run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

            - name: Get version from dispatch
              if: github.event_name == 'workflow_dispatch'
              run: echo "version=${{ github.event.inputs.version }}" >> "$GITHUB_ENV"

            - name: Set version
              id: version
              run: echo "version=${{ env.version }}" >> $GITHUB_OUTPUT

    build:
        needs: version
        runs-on: ${{ matrix.os }}-latest
        strategy:
            matrix:
                os: [ubuntu, windows, macos]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12
                  cache: "pip"

            - name: Install packages
              run: pip install -r requirements.txt

            - name: Build
              run: pyinstaller -F -n sudoku-${{ needs.version.outputs.version }}-${{ matrix.os }} src/gui.py

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.os }}
                  path: dist/sudoku-*

    release:
        name: Draft release
        runs-on: ubuntu-latest
        needs:
            - version
            - build
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  name: sudoku ${{ needs.version.outputs.version }}
                  tag_name: ${{ needs.version.outputs.version }}
                  token: ${{ SECRETS.GITHUB_TOKEN }}
                  fail_on_unmatched_files: true
                  files: ./*/sudoku-*
                  draft: true
